version: "3.9"

services:
  bun-elysia:
    container_name: bun-elysia
    image: bun-elysia
    build:
      context: .
    ports:
      - "3000:3000"
    volumes:
      - ./uploads:/app/uploads
    env_file:
      - .env
    restart: unless-stopped
